### ISSUE TITLE
XSLT Warning PEPPOL-EN16931-UBL.xslt Rule - Function should use xsl:sequence rather than xsl:value-of

### ISSUE THREAD

**Issue by traker9999** [phax/ph-bdve-rules#3]
Hello,

we are using BDVE for validation of OpenPeppol BIS 3 Invoice and CreditNote. The latest xslt Version leads to a compiler warning:
```
Warning at function u:slack on line 31 of PEPPOL-EN16931-UBL.xslt:
  SXWN9000  A function that computes atomic values should use xsl:sequence rather than xsl:value-of
```
The Warning is thrown here: [PEPPOL-EN16931-UBL.xslt](https://github.com/phax/ph-bdve-rules/blob/770fcc60924cb36843c42a9ea0c5b26754e0cd68/ph-bdve-rules-peppol/src/main/resources/openpeppol/3.10.1/xslt/PEPPOL-EN16931-UBL.xslt#L35)

We test it using Saxon 10.0 HE. Is there a possible fix for it? Thank you

**Comment by phax** [comment]
Hi @traker9999  thanks for pinging 👍 
Luckily this is just a warning and therefore not blocking the validation of business documents.
As I am not the author of these rules may I ask you to report this error directly to them? According to https://github.com/OpenPEPPOL/peppol-bis-invoice-3 you should use the Peppol ServiceDesk (https://openpeppol.atlassian.net/servicedesk/customer/portal/1) to so.
Thanks.

**Comment by traker9999** [comment]
Thank you for your answer. We will do so. Kind regards
